int32 camera_number
api_interfaces/POI poi
int32 capture_type #Can be 0 for still image or 1 for video
MovementRoutine movement_routine #Used for video capture if applicable
---
string output
string info
---
string feedback
int32[] ptz_positional_data